########## Testcase 0: Failed ##########
Expected Output: 
Cycle doesn't exists.

Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Directed.addEdge(Solution.java:61)
	at Directed.<init>(Solution.java:34)
	at Solution.main(Solution.java:171)
----------------------------------------

########## Testcase 1: Failed ##########
Expected Output: 
Cycle doesn't exists.

Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Directed.addEdge(Solution.java:61)
	at Directed.<init>(Solution.java:34)
	at Solution.main(Solution.java:171)
----------------------------------------

########## Testcase 2: Failed ##########
Expected Output: 
Cycle exists.

Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Directed.addEdge(Solution.java:61)
	at Directed.<init>(Solution.java:34)
	at Solution.main(Solution.java:171)
----------------------------------------

########## Testcase 3: Failed ##########
Expected Output: 
Cycle exists.

Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Directed.addEdge(Solution.java:61)
	at Directed.<init>(Solution.java:34)
	at Solution.main(Solution.java:171)
----------------------------------------

########## Testcase 4: Failed ##########
Expected Output: 
Cycle exists.

Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Directed.addEdge(Solution.java:61)
	at Directed.<init>(Solution.java:34)
	at Solution.main(Solution.java:171)
----------------------------------------

########## Testcase 5: Failed ##########
Expected Output: 
Cycle exists.

Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Directed.addEdge(Solution.java:61)
	at Directed.<init>(Solution.java:34)
	at Solution.main(Solution.java:171)
----------------------------------------

########## Testcase 6: Failed ##########
Expected Output: 
Cycle doesn't exists.

Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Directed.addEdge(Solution.java:61)
	at Directed.<init>(Solution.java:34)
	at Solution.main(Solution.java:171)
----------------------------------------

########## Testcase 7: Failed ##########
Expected Output: 
Cycle exists.

Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at Directed.addEdge(Solution.java:61)
	at Directed.<init>(Solution.java:34)
	at Solution.main(Solution.java:171)
----------------------------------------

